### PR TITLE
Labeler Overhaul

### PR DESCRIPTION
**Pull request by TheSCREWEDSoftware**
Removal of the existing workflow for `labeler.yml` 

And addition of the labels upon creation for their respective issues.

Example [here](https://github.com/TheSCREWEDSoftware/labeler-test/issues) Ignore the label names.

Edit: This will place the label defined upon creating the issue. Does not have delay and it's added under the author name.

`Ryan added Website to this issue`. Since we do not have dynmaic issues/prs, labels in CC no need to use the labeler

### CODE REVIEW

**Review by Yehonal — APPROVED** [review]
LGTM! Thanks!

But I'd ping the author of the labeler.yml possibly

**Comment by TheSCREWEDSoftware** [comment]
Do you mean the person that implemented into CC or the author that made the labeler?

Because the author's labeler has no issues (just that for CC we dont need a bot to implement the labels, since they are either X or Y depending on the form filled)

**Comment by Yehonal** [comment]
> Do you mean the person that implemented into CC or the author that made the labeler?
> 
> Because the author's labeler has no issues (just that for CC we dont need a bot to implement the labels, since they are either X or Y depending on the form filled)

@locus313 implemented it

However, nevermind. If everybody is ok with this I would proceed :)

**Comment by Yehonal** [comment]
cc @Rorschach91

**Comment by Rorschach91** [comment]
No objection.

**Pull request merged**
